import type { Product } from './types';

// Används när Supabase inte är kopplat ännu, så att sidan fungerar direkt efter deploy.
// Samma produkter läggs in i databasen av supabase/schema.sql.
export const SEED_PRODUCTS: Product[] = [
  {
    id: 'seed-nf8',
    sku: 'NG-201080',
    slug: 'nordgrad-nf-8-bankfritos-8-liter',
    name: 'NF-8 Bänkfritös 8 L',
    brand: 'Nordgrad',
    category: 'fritoser',
    subcategory: 'Bänkfritös',
    short: 'Den fritös vi säljer mest. Liten nog för bänken, stark nog för en hel kväll med pommes.',
    description:
      'NF-8 är en bänkfritös för café, food truck och mindre restaurang. Oljekaret på 8 liter och 3,2 kW-elementet ger snabb återhämtning mellan satserna, så att andra korgen blir lika krispig som den första.\n\nElementet fälls upp för rengöring och karet lyfts ur. Termostaten går mellan 50 och 190 °C, och ett separat överhettningsskydd stänger av om oljan blir för varm. Kopplas i ett vanligt 230V-uttag.',
    price: 3490,
    compare_price: 3990,
    stock: 32,
    featured: true,
    image_url: null,
    art: 'fryer',
    specs: [
      { label: 'Kapacitet', value: 'ca 6 kg pommes/tim' },
      { label: 'Volym', value: '8 L' },
      { label: 'Effekt', value: '3,2 kW' },
      { label: 'Temperatur', value: '50–190 °C' },
      { label: 'Korgar', value: '1' },
      { label: 'Anslutning', value: '230V 1N~' },
      { label: 'Mått (B×D×H)', value: '290 × 460 × 340 mm' },
    ],
    sort_order: 1,
    created_at: '2026-09-01T08:00:00Z',
  },
  {
    id: 'seed-gf18',
    sku: 'NG-201180',
    slug: 'nordgrad-gf-18-golvfritos-18-liter',
    name: 'GF-18 Golvfritös 18 L',
    brand: 'Nordgrad',
    category: 'fritoser',
    subcategory: 'Golvfritös',
    short: 'För grill, hamburgerrestaurang och pizzeria där fritösen går hela passet.',
    description:
      'GF-18 är en fristående golvfritös med 18 liters kar och två korgar, så att du kan köra två portioner parallellt. Med 15 kW återhämtar sig oljan snabbt även när frysta pommes läggs i.\n\nKallzonen under elementen samlar smulor så att oljan håller längre. Oljan töms via en tappkran i skåpet, direkt i ett uppsamlingskärl.',
    price: 18900,
    compare_price: null,
    stock: 9,
    featured: true,
    image_url: null,
    art: 'fryer',
    specs: [
      { label: 'Kapacitet', value: 'ca 30 kg pommes/tim' },
      { label: 'Volym', value: '18 L' },
      { label: 'Effekt', value: '15 kW' },
      { label: 'Temperatur', value: '50–190 °C' },
      { label: 'Korgar', value: '2' },
      { label: 'Anslutning', value: '400V 3N~' },
      { label: 'Mått (B×D×H)', value: '400 × 700 × 900 mm' },
    ],
    sort_order: 2,
    created_at: '2026-09-01T08:00:00Z',
  },
  {
    id: 'seed-fd50',
    sku: 'NG-104500',
    slug: 'nordgrad-fd-50-frontmatad-diskmaskin',
    name: 'FD-50 Frontmatad diskmaskin',
    brand: 'Nordgrad',
    category: 'diskmaskiner',
    subcategory: 'Frontmatad / underbänk',
    short: 'Får plats under bänken och klarar lunchrusningen i café, pizzeria och mindre restaurang.',
    description:
      'FD-50 är en frontmatad diskmaskin för kök med 40–80 kuvert per pass. Den tar standardkorgar 500 × 500 mm och har tre program för allt från glas till kastruller.\n\nSköljpumpen håller sköljvattnet på 85 °C även när maskinen körs tätt, och doseringen av disk- och sköljmedel är inbyggd.',
    price: 24900,
    compare_price: 28900,
    stock: 14,
    featured: true,
    image_url: null,
    art: 'front',
    specs: [
      { label: 'Kapacitet', value: '30–40 korgar/tim' },
      { label: 'Korgstorlek', value: '500 × 500 mm' },
      { label: 'Effekt', value: '6,7 kW' },
      { label: 'Program', value: '90 / 120 / 180 s' },
      { label: 'Instickshöjd', value: '330 mm' },
      { label: 'Sköljtemperatur', value: '85 °C' },
      { label: 'Anslutning', value: '400V 3N~' },
      { label: 'Mått (B×D×H)', value: '600 × 600 × 820 mm' },
    ],
    sort_order: 3,
    created_at: '2026-09-01T08:00:00Z',
  },
  {
    id: 'seed-ku4',
    sku: 'NG-301040',
    slug: 'nordgrad-ku-4-konvektionsugn-4-plat',
    name: 'KU-4 Konvektionsugn med ånga',
    brand: 'Nordgrad',
    category: 'ugnar',
    subcategory: 'Konvektionsugn',
    short: 'Bakar, steker och värmer fyra plåtar samtidigt. Ångan håller kött saftigt och bröd luftigt.',
    description:
      'KU-4 tar fyra GN 1/1 eller bakplåtar 600 × 400 mm. Två fläktar med automatisk riktningsväxling ger jämn värme på alla plåtar, så du slipper vända dem.\n\nBefuktningen stängs på och av med en knapp. Luckan har dubbelglas som håller utsidan sval, och den öppnas sidledes så att den inte tar plats framför ugnen.',
    price: 21900,
    compare_price: null,
    stock: 6,
    featured: true,
    image_url: null,
    art: 'oven',
    specs: [
      { label: 'Kapacitet', value: '4 × GN 1/1' },
      { label: 'Effekt', value: '6,4 kW' },
      { label: 'Temperatur', value: '50–270 °C' },
      { label: 'Plåtavstånd', value: '75 mm' },
      { label: 'Befuktning', value: 'Ja' },
      { label: 'Anslutning', value: '400V 3N~' },
      { label: 'Mått (B×D×H)', value: '780 × 720 × 580 mm' },
    ],
    sort_order: 4,
    created_at: '2026-09-01T08:00:00Z',
  },
  {
    id: 'seed-kb2',
    sku: 'NG-401360',
    slug: 'nordgrad-kb-2-kylbank-2-dorrar',
    name: 'KB-2 Kylbänk 2 dörrar',
    brand: 'Nordgrad',
    category: 'kyl',
    subcategory: 'Kylbänk',
    short: 'Arbetsbänk och kyl i ett. Råvarorna ligger kalla precis där du jobbar.',
    description:
      'KB-2 har två dörrar för GN 1/1 och en arbetsyta i rostfritt stål. Kylaggregatet går med det naturliga köldmediet R290, drar lite ström och håller +2 till +8 °C även när dörrarna öppnas ofta.\n\nDörrarna stänger själva, och listerna går att byta utan verktyg. Kopplas i ett vanligt 230V-uttag.',
    price: 14900,
    compare_price: 16900,
    stock: 11,
    featured: true,
    image_url: null,
    art: 'fridge',
    specs: [
      { label: 'Volym', value: '260 L' },
      { label: 'Temperatur', value: '+2 till +8 °C' },
      { label: 'Effekt', value: '0,35 kW' },
      { label: 'Dörrar', value: '2' },
      { label: 'Köldmedium', value: 'R290' },
      { label: 'Anslutning', value: '230V 1N~' },
      { label: 'Mått (B×D×H)', value: '1360 × 700 × 850 mm' },
    ],
    sort_order: 5,
    created_at: '2026-09-01T08:00:00Z',
  },
];
