import type { Product } from './types';

// Används när Supabase inte är kopplat ännu, så att sidan fungerar direkt efter deploy.
// Samma fyra produkter läggs in i databasen av supabase/schema.sql.
export const SEED_PRODUCTS: Product[] = [
  {
    id: 'seed-fd50',
    slug: 'nordgrad-fd-50-frontmatad-diskmaskin',
    name: 'FD-50 Frontmatad diskmaskin',
    brand: 'Nordgrad',
    category: 'diskmaskiner',
    subcategory: 'Fristående / underbänk',
    short: 'Vår mest sålda diskmaskin. Klarar lunchrusningen i café, pizzeria och mindre restaurang.',
    description:
      'FD-50 är en fristående frontmatad diskmaskin för kök med 40–80 kuvert per pass. Den får plats under en vanlig bänk och tar standardkorgar 500×500 mm. Tre program täcker allt från glas till kastruller, och sköljpumpen håller sköljtemperaturen jämn på 85 °C även när maskinen körs tätt. Diskmedels- och sköljmedelsdosering är inbyggd.',
    price: 24900,
    compare_price: 28900,
    stock: 14,
    featured: true,
    image_url: null,
    art: 'front',
    specs: [
      { label: 'Korgstorlek', value: '500 × 500 mm' },
      { label: 'Kapacitet', value: '30–40 korgar/tim' },
      { label: 'Program', value: '90 / 120 / 180 s' },
      { label: 'Instickshöjd', value: '330 mm' },
      { label: 'Sköljtemperatur', value: '85 °C' },
      { label: 'Anslutning', value: '400V 3N~ / 6,7 kW' },
      { label: 'Mått (B×D×H)', value: '600 × 600 × 820 mm' },
    ],
    sort_order: 1,
    created_at: '2026-09-01T08:00:00Z',
  },
  {
    id: 'seed-fd50s',
    slug: 'nordgrad-fd-50s-frontmatad-diskmaskin-avhardare',
    name: 'FD-50S Frontmatad diskmaskin med avhärdare',
    brand: 'Nordgrad',
    category: 'diskmaskiner',
    subcategory: 'Fristående / underbänk',
    short: 'Samma arbetshäst som FD-50, med inbyggd avhärdare och avloppspump.',
    description:
      'FD-50S är för kök med hårt vatten eller där avloppet sitter högt. Den inbyggda avhärdaren skyddar elementen mot kalk och ger fläckfria glas utan eftertorkning. Avloppspumpen gör att maskinen kan placeras fritt i köket. Dubbelväggig isolerad lucka håller ljudnivån nere och värmen inne.',
    price: 31900,
    compare_price: null,
    stock: 8,
    featured: true,
    image_url: null,
    art: 'front',
    specs: [
      { label: 'Korgstorlek', value: '500 × 500 mm' },
      { label: 'Kapacitet', value: '30–40 korgar/tim' },
      { label: 'Program', value: '90 / 120 / 180 s' },
      { label: 'Instickshöjd', value: '330 mm' },
      { label: 'Avhärdare', value: 'Inbyggd' },
      { label: 'Avloppspump', value: 'Ja' },
      { label: 'Anslutning', value: '400V 3N~ / 6,7 kW' },
      { label: 'Mått (B×D×H)', value: '600 × 620 × 850 mm' },
    ],
    sort_order: 2,
    created_at: '2026-09-01T08:00:00Z',
  },
  {
    id: 'seed-hd60',
    slug: 'nordgrad-hd-60-huvdiskmaskin',
    name: 'HD-60 Huvdiskmaskin',
    brand: 'Nordgrad',
    category: 'diskmaskiner',
    subcategory: 'Huvdiskmaskin',
    short: 'Hög kapacitet för restauranger, skolkök och hotell. Lyft huven, skjut in korgen, klart.',
    description:
      'HD-60 är en genomskjutsmaskin som byggs ihop med till- och frånbänk till en diskstation. Huven startar programmet automatiskt när den fälls ned. Med 60 korgar i timmen och 440 mm instickshöjd tar den både GN-kantiner och bakplåtar. Dubbla diskarmar i rostfritt ger jämnt resultat i hela korgen.',
    price: 49900,
    compare_price: 54900,
    stock: 5,
    featured: true,
    image_url: null,
    art: 'hood',
    specs: [
      { label: 'Korgstorlek', value: '500 × 500 mm' },
      { label: 'Kapacitet', value: 'upp till 60 korgar/tim' },
      { label: 'Program', value: '60 / 90 / 180 s' },
      { label: 'Instickshöjd', value: '440 mm' },
      { label: 'Start', value: 'Automatisk vid stängd huv' },
      { label: 'Anslutning', value: '400V 3N~ / 9,8 kW' },
      { label: 'Mått (B×D×H)', value: '680 × 760 × 1480 mm (öppen huv 1930 mm)' },
    ],
    sort_order: 3,
    created_at: '2026-09-01T08:00:00Z',
  },
  {
    id: 'seed-gd40',
    slug: 'nordgrad-gd-40-glasdiskmaskin',
    name: 'GD-40 Glasdiskmaskin',
    brand: 'Nordgrad',
    category: 'diskmaskiner',
    subcategory: 'Glasdiskmaskin',
    short: 'Kompakt glasdiskare för bar och café. Får plats under bardisken.',
    description:
      'GD-40 är byggd för glas och koppar. Lägre disktemperatur och mjukt sköljtryck skonar glasen, och ett 120-sekundersprogram gör att baren aldrig står utan rena glas. Kompakta mått på 450 mm bredd gör den lätt att placera under en bardisk.',
    price: 16900,
    compare_price: null,
    stock: 20,
    featured: true,
    image_url: null,
    art: 'glass',
    specs: [
      { label: 'Korgstorlek', value: '400 × 400 mm' },
      { label: 'Kapacitet', value: '30 korgar/tim' },
      { label: 'Program', value: '120 / 180 s' },
      { label: 'Instickshöjd', value: '270 mm' },
      { label: 'Anslutning', value: '230V 1N~ / 3,1 kW' },
      { label: 'Mått (B×D×H)', value: '450 × 530 × 700 mm' },
    ],
    sort_order: 4,
    created_at: '2026-09-01T08:00:00Z',
  },
];
